function Maug = M_aug_func_slide(in1,dx,muk)
%M_aug_func_slide
%    Maug = M_aug_func_slide(IN1,DX,MUK)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Feb-2025 14:56:04

l = in1(1,:);
qB = in1(2,:);
t2 = cos(qB);
t3 = sin(qB);
t4 = t2.*(9.4e+1./5.0);
t5 = l.*t3.*(9.4e+1./5.0);
t6 = -t5;
Maug = reshape([t4,t3.*(9.4e+1./5.0),9.4e+1./5.0,0.0,t6,l.*t4,0.0,l.^2.*(9.4e+1./5.0),1.88238e+1,0.0,t4,t6,(dx.*muk)./(abs(dx)+1.0e-5),-1.0,0.0,0.0],[4,4]);
end
