function f = f_func_stick(in1,in2,in3)
%F_FUNC_STICK
%    F = F_FUNC_STICK(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Feb-2025 14:50:14

Fbh_y = in3(5,:);
Fdh_x = in3(1,:);
Fdh_y = in3(2,:);
Fdl_x = in3(3,:);
Fdl_y = in3(4,:);
T_w = in3(6,:);
Tau = in1(3,:);
dl = in2(1,:);
dqB = in2(2,:);
l = in1(1,:);
ldes = in1(4,:);
qB = in1(2,:);
t2 = cos(qB);
t3 = sin(qB);
t4 = dqB.^2;
f = [Fdh_x+Fdl_x+dl.*dqB.*t3.*(1.88e+2./5.0)+l.*t2.*t4.*(9.4e+1./5.0);Fbh_y+Fdh_y+Fdl_y-dl.*dqB.*t2.*(1.88e+2./5.0)+l.*t3.*t4.*(9.4e+1./5.0)-1.8447324e+2;l.*-8.003e+3+ldes.*8.003e+3+t3.*(Fbh_y+Fdh_y+Fdl_y-1.8424e+2)+l.*t4.*(9.4e+1./5.0)+t2.*(Fdh_x+Fdl_x);T_w+Tau+l.*t2.*(Fbh_y+Fdh_y-1.8424e+2)-Fdh_x.*l.*t3-Fdl_x.*l.*t3.*5.0e-1+Fdl_y.*l.*t2.*5.0e-1-dl.*dqB.*l.*(1.88e+2./5.0)];
end
